services:
  oracle:
    # See the 'docker' subdirectory for the content of this image.
    # Note that we are using the sha256 hash of the image to ensure integrity.
    image: ghcr.io/oasisprotocol/demo-rofl:v2@sha256:17dc804783f9a200de6d6d88e24f86a71e18beb33433a8f1a9a3698331940fe0
    build:
      context: docker
    platform: linux/amd64
    environment:
      # Address of the oracle contract deployed on Sapphire.
      - CONTRACT_ADDRESS=1234845aaB7b6CD88c7fAd9E9E1cf07638805b20
      # Ticker.
      - TICKER=ROSEUSDT
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock

  frontend:
    image: docker.io/hashicorp/http-echo:latest@sha256:fcb75f691c8b0414d670ae570240cbf95502cc18a9ba57e982ecac589760a186
    platform: linux/amd64
    environment:
      ECHO_TEXT: "hello rofl world (${ROFL_PROXY_HOST})"
    ports:
      - "5678:5678"
    annotations:
      net.oasis.proxy.ports.5678.custom_domain: demo.rofl.build
